export const CAGAYAN_LOCATION_TREE = [
  {
    "name": "Abulug",
    "barangays": [
      "Alinunu",
      "Bagu",
      "Banguian",
      "Calog Norte",
      "Calog Sur",
      "Canayun",
      "Centro",
      "Dana-Ili",
      "Guiddam",
      "Libertad",
      "Lucban",
      "Pinili",
      "San Agustin",
      "San Julian",
      "Santa Filomena",
      "Santa Rosa",
      "Santo Tomas",
      "Siguiran",
      "Simayung",
      "Sirit"
    ]
  },
  {
    "name": "Alcala",
    "barangays": [
      "Abbeg",
      "Afusing Bato",
      "Afusing Daga",
      "Agani",
      "Baculod",
      "Baybayog",
      "Cabuluan",
      "Calantac",
      "Carallangan",
      "Centro Norte",
      "Centro Sur",
      "Dalaoig",
      "Damurog",
      "Jurisdiction",
      "Malalatan",
      "Maraburab",
      "Masin",
      "Pagbangkeruan",
      "Pared",
      "Piggatan",
      "Pinopoc",
      "Pussian",
      "San Esteban",
      "Tamban",
      "Tupang"
    ]
  },
  {
    "name": "Allacapan",
    "barangays": [
      "Bessang",
      "Binobongan",
      "Bulo",
      "Burot",
      "Capagaran",
      "Capalutan",
      "Capanickian Norte",
      "Capanickian Sur",
      "Cataratan",
      "Centro East",
      "Centro West",
      "Daan-Ili",
      "Dagupan",
      "Dalayap",
      "Gagaddangan",
      "Iringan",
      "Labben",
      "Maluyo",
      "Mapurao",
      "Matucay",
      "Nagattatan",
      "Pacac",
      "San Juan",
      "Silangan",
      "Tamboli",
      "Tubel",
      "Utan"
    ]
  },
  {
    "name": "Amulung",
    "barangays": [
      "Abolo",
      "Agguirit",
      "Alitungtung",
      "Annabuculan",
      "Annafatan",
      "Anquiray",
      "Babayuan",
      "Baccuit",
      "Bacring",
      "Baculod",
      "Balauini",
      "Bauan",
      "Bayabat",
      "Calamagui",
      "Calasitan",
      "Calintaan",
      "Caratacat",
      "Casingsingan Norte",
      "Casingsingan Sur",
      "Catarauan",
      "Centro",
      "Concepcion",
      "Cordova",
      "Dadda",
      "Dafunganay",
      "Dondo",
      "Dugayung",
      "Estefania",
      "Fugu",
      "Gabut",
      "Gangauan",
      "Goran",
      "Jurisdiccion",
      "La Suerte",
      "Logung",
      "Mangagan",
      "Masical",
      "Nagragoan",
      "Namuac",
      "Pacac-Grande",
      "Pacac-Pequeño",
      "Palayag",
      "Pangul",
      "Tacca",
      "Tana",
      "Tanlagan",
      "Unimay"
    ]
  },
  {
    "name": "Aparri",
    "barangays": [
      "Backiling",
      "Bangag",
      "Binalan",
      "Bisagu",
      "Bukid",
      "Bulala Norte",
      "Bulala Sur",
      "Bulala-Baculud",
      "Calaogan",
      "Capas",
      "Centro East",
      "Centro West",
      "Daddac",
      "Dodongan",
      "Fugu",
      "Gaddani",
      "Linao",
      "Macanaya",
      "Maura",
      "Minanga",
      "Navagan",
      "Navayugan",
      "Paddaya",
      "Paruddun Norte",
      "Paruddun Sur",
      "Plaza",
      "Poblacion Formosa (Zone 2)",
      "Poblacion Macanaya (Zone 4)",
      "Poblacion Navaling (Zone 7)",
      "Poblacion Plaza (Zone 5)",
      "Poblacion Rivera (Zone 6)",
      "Poblacion San Jose (Zone 1)",
      "Poblacion Torres (Zone 3)",
      "Punta",
      "San Antonio",
      "San Roque",
      "Sanja",
      "Tallungan",
      "Toran",
      "Uguis",
      "Viga",
      "Zimbiez"
    ]
  },
  {
    "name": "Baggao",
    "barangays": [
      "Adaoag",
      "Agaman",
      "Agaman Norte",
      "Agaman Sur",
      "Alba",
      "Amparing",
      "Annayatan",
      "Asassi",
      "Asinga-Via",
      "Awallan",
      "Bacagan",
      "Bagunot",
      "Barsat East",
      "Barsat West",
      "Bitag Grande",
      "Bitag Pequeño",
      "Bunugan",
      "C Verzosa",
      "Carupian",
      "Catugay",
      "Dabbac Grande",
      "Dalin",
      "Dalla",
      "Hacienda Intal",
      "Ibulo",
      "Imurong",
      "J. Pallagao",
      "Lasilat",
      "Mabini",
      "Masical",
      "Mocag",
      "Nangalinan",
      "Poblacion",
      "Remus",
      "San Antonio",
      "San Francisco",
      "San Isidro",
      "San Jose",
      "San Miguel",
      "San Vicente",
      "Santa Margarita",
      "Santor",
      "Taguing",
      "Taguntungan",
      "Tallang",
      "Taytay",
      "Temblique",
      "Tungal"
    ]
  },
  {
    "name": "Ballesteros",
    "barangays": [
      "Ammubuan",
      "Baran",
      "Cabaritan East",
      "Cabaritan West",
      "Cabayaosan",
      "Centro East",
      "Centro West",
      "Fugu",
      "Mabuttal East",
      "Mabuttal West",
      "Nararagan",
      "Palloc",
      "Payangan",
      "San Juan",
      "Santa Cruz",
      "Sitti",
      "Tabba",
      "Tamucco",
      "Voluntario"
    ]
  },
  {
    "name": "Buguey",
    "barangays": [
      "Antiporda",
      "Ballang",
      "Balza",
      "Cabaritan",
      "Calamegistan",
      "Caronauan",
      "Centro",
      "Dalaya",
      "Fugu",
      "Leron",
      "Minanga",
      "Paddaya Este",
      "Paddaya Weste",
      "Pattao",
      "Quinawegan",
      "Remebias",
      "San Isidro",
      "San Jose",
      "San Lorenzo",
      "San Roque",
      "San Vicente",
      "Santa Maria",
      "Santa Teresita",
      "Tabbac",
      "Villa Blanca",
      "Villa Cielo",
      "Villa Gomez",
      "Villa Leonor",
      "Villa Mercedes",
      "Zaragosa"
    ]
  },
  {
    "name": "Calayan",
    "barangays": [
      "Babuyan Claro",
      "Balatubat",
      "Cabudadan",
      "Camiguin",
      "Centro II",
      "Dadao",
      "Dibay",
      "Dilam",
      "Magsidel",
      "Minabel",
      "Naguilian",
      "Poblacion"
    ]
  },
  {
    "name": "Camalaniugan",
    "barangays": [
      "Abagao",
      "Afunan Cabayu",
      "Agusi",
      "Alilinu",
      "Alucao",
      "Baggao",
      "Biay",
      "Bulala",
      "Casagan",
      "Catotoran Norte",
      "Catotoran Sur",
      "Centro East",
      "Centro West",
      "Dacal",
      "Dacallafugu",
      "Fusina",
      "Gangcu",
      "Luec",
      "Naboturan",
      "Paraddaya",
      "Sisin",
      "Suyo",
      "Tagalag",
      "Tangatan",
      "Tueg",
      "Tulapa",
      "Unisan",
      "Ziminila"
    ]
  },
  {
    "name": "Claveria",
    "barangays": [
      "Alimoan",
      "Bacsay Cataraoan Norte",
      "Bacsay Cataraoan Sur",
      "Bacsay Mapulapula",
      "Bilibigao",
      "Buenavista",
      "Bulala",
      "Cabiseraan",
      "Caculutanan",
      "Cadaclan",
      "D. Leano",
      "Kilkiling",
      "Lablabig",
      "Luzon",
      "Mababangug",
      "Malasin",
      "Nagsanga",
      "Pata East",
      "Pata West",
      "Pawac",
      "Pinas",
      "Plaza",
      "Poblacion 1",
      "Poblacion 2",
      "Poblacion 3",
      "Poblacion 4",
      "Poblacion 5",
      "Poblacion 6",
      "Poblacion 7",
      "Poblacion 8",
      "San Antonio",
      "San Isidro",
      "San Jose",
      "Santa Filomena",
      "Santa Maria",
      "Santiago",
      "Santo Niño",
      "Sasil",
      "Taggat Norte",
      "Taggat Sur",
      "Union"
    ]
  },
  {
    "name": "Enrile",
    "barangays": [
      "Alibago",
      "Barangay I",
      "Barangay II",
      "Barangay III",
      "Barangay IV",
      "Divisoria",
      "Inga",
      "Lemu",
      "Liwan Norte",
      "Liwan Sur",
      "Maddarulug",
      "Magalalag East",
      "Magalalag West",
      "Marba",
      "Metba",
      "Roma Norte",
      "Roma Sur",
      "San Antonio",
      "San Jose",
      "San Roque",
      "Santa Maria",
      "Taguiporo"
    ]
  },
  {
    "name": "Gattaran",
    "barangays": [
      "Abra",
      "Aguiguican",
      "Bolos",
      "Calaoagan Bassit",
      "Calaoagan Dackel",
      "Capissayan",
      "Capungasan",
      "Casicallan Norte",
      "Casicallan Sur",
      "Centro Norte",
      "Centro Sur",
      "Cullit",
      "Cumao",
      "Dummun",
      "Fugu",
      "Gadu",
      "Ganzano",
      "Guising",
      "Lanna",
      "Lapogan",
      "Lingu",
      "Mabuno",
      "Madatag",
      "Maura",
      "Mina",
      "Nabaccayan",
      "Naddungan",
      "Naganacan",
      "Nangalisan",
      "Nassiping",
      "Newagan",
      "Palagao Norte",
      "Palagao Sur",
      "Panto",
      "Piña Norte",
      "Piña Sur",
      "San Carlos",
      "San Esteban",
      "San Josen",
      "San Vicente",
      "Santa Ana",
      "Sidem",
      "Simundac",
      "Taguing",
      "Takiki",
      "Taligan",
      "Tanglagan",
      "Tubungan East",
      "Tubungan West",
      "Zinundungan"
    ]
  },
  {
    "name": "Gonzaga",
    "barangays": [
      "Amio",
      "Batangan",
      "Baua",
      "Cabiraoan",
      "Cabiseraan",
      "Callao",
      "Caroan",
      "Casitan",
      "Flourishing",
      "Ipil",
      "Magrafil",
      "Matatalahib",
      "Minanga",
      "Paradise",
      "Pateng",
      "Progressive",
      "Rebecca",
      "San Roque",
      "Santa Clara",
      "Santa Cruz",
      "Santa Maria",
      "Smart",
      "Tapel",
      "Unyon",
      "Woodside"
    ]
  },
  {
    "name": "Iguig",
    "barangays": [
      "Ajat",
      "Atulu",
      "Baculud",
      "Bayo",
      "Campo",
      "Dumpao",
      "Gammad",
      "Garab",
      "Malabbac",
      "Manaquil",
      "Minanga",
      "Nattanzan",
      "Redondo",
      "Salamague",
      "San Christopher",
      "San Esteban",
      "San Isidro",
      "San Josen",
      "San Quintin",
      "San Vicente",
      "Santa Barbara",
      "Santa Maria",
      "Santa Teresa"
    ]
  },
  {
    "name": "Lal-lo",
    "barangays": [
      "Abagao",
      "Alaguia",
      "Alucao",
      "Bagumbayan",
      "Barrio",
      "Bicud",
      "Binag",
      "Cabayabasan",
      "Cagayanon",
      "Calasitan",
      "Catayauan",
      "Centro",
      "Dalaya",
      "Fabrica",
      "Fusina",
      "Jurisdiction",
      "Lalafugan",
      "Logac",
      "Magapit",
      "Malanao",
      "Malasin",
      "Maxingal",
      "Naguilian",
      "Opisina",
      "Parana",
      "Reforma",
      "San Antonio",
      "San Jose",
      "San Lorenzo",
      "San Mariano",
      "San Roque",
      "Santa Maria",
      "Santa Teresa",
      "Tucalana",
      "Valentino"
    ]
  },
  {
    "name": "Lasam",
    "barangays": [
      "Aggunetan",
      "Alannay",
      "Battung",
      "Calapangan",
      "Callao",
      "Campo",
      "Centro I",
      "Centro II",
      "Centro III",
      "Cottaruan",
      "Finugu",
      "Gumpam",
      "Ignacio B. Jurado",
      "Magsaysay",
      "Malinta",
      "Minanga",
      "Nabannagan Norte",
      "Nabannagan Sur",
      "New Cuyo",
      "Nicolas Agatep",
      "Peru",
      "San Jose",
      "Sicalao",
      "Sinippil",
      "Taguiporo",
      "Taligan",
      "Tucalan",
      "Tulip",
      "Viga",
      "Western"
    ]
  },
  {
    "name": "Pamplona",
    "barangays": [
      "Abanqueruan",
      "Allasitan",
      "Bagu",
      "Basi",
      "Bidduang",
      "Cabaggan",
      "Capalallan",
      "Casitan",
      "Centro",
      "Curva",
      "Gattu",
      "Masi",
      "Naguilian",
      "Natallangan",
      "San Juan",
      "Santa Cruz",
      "Santa Maria",
      "Tupanna"
    ]
  },
  {
    "name": "Peñablanca",
    "barangays": [
      "Agani",
      "Aggugaddan",
      "Alimanao",
      "Bugatay",
      "Cabasan",
      "Cabbo",
      "Callao",
      "Camasi",
      "Centro",
      "Dodan",
      "Lapi",
      "Malibabag",
      "Manga",
      "Minanga",
      "Nabbabalayan",
      "Nanguilattan",
      "Parabba",
      "Patagueleg",
      "Quibal",
      "San Jose",
      "San Roque",
      "Sisim",
      "Tagga",
      "Tallag"
    ]
  },
  {
    "name": "Piat",
    "barangays": [
      "Apayao",
      "Aquib",
      "Baung",
      "Calaoagan",
      "Dugayung",
      "Macapil",
      "Maguilling",
      "Minanga",
      "Poblacion I",
      "Poblacion II",
      "San Juan",
      "Santa Barbara",
      "Santo Domingo",
      "Sicat",
      "Tallub",
      "Taza",
      "Villa Maria",
      "Wacal"
    ]
  },
  {
    "name": "Rizal",
    "barangays": [
      "Anagguan",
      "Anungu",
      "Anurturu",
      "Babuestan",
      "Balani",
      "Battung",
      "Baua",
      "Buluan",
      "Cambabangan",
      "Capacuan",
      "Dungeg",
      "Gaddang",
      "Gungona",
      "Illuru Norte",
      "Illuru Sur",
      "Lagum",
      "Liwan",
      "Maddalero",
      "Masi",
      "Minanga",
      "Nanungaran",
      "Pasingan",
      "Poblacion",
      "San Juan",
      "Simo",
      "Sinicking",
      "Sittio",
      "Tuyung",
      "Viga"
    ]
  },
  {
    "name": "Sanchez-Mira",
    "barangays": [
      "Bangan",
      "Callungan",
      "Centro I",
      "Centro II",
      "Dacal",
      "Dagueray",
      "Dammang",
      "Kittag",
      "Langagan",
      "Magacan",
      "Marzan",
      "Masisit",
      "Nagrangtayan",
      "Namuac",
      "San Andres",
      "Santiago",
      "Santor",
      "Tokitok"
    ]
  },
  {
    "name": "Santa Ana",
    "barangays": [
      "Batu-Parada",
      "Casagan",
      "Casambalangan",
      "Centro",
      "Diora-Zinungan",
      "Dungeg",
      "Kapanikian",
      "Marede",
      "Palawig",
      "Patunungan",
      "Rapuli",
      "San Vicente",
      "Santa Clara",
      "Santa Cruz",
      "Tangatan",
      "Visitacion"
    ]
  },
  {
    "name": "Santa Praxedes",
    "barangays": [
      "Cadongdongan",
      "Capacuan",
      "Centro I",
      "Centro II",
      "Macatel",
      "Portabaga",
      "Salungsong",
      "San Juan",
      "San Miguel",
      "Sicul"
    ]
  },
  {
    "name": "Santa Teresita",
    "barangays": [
      "Alucao",
      "Aridawen",
      "Buyun",
      "Caniugan",
      "Centro East",
      "Centro West",
      "Dungeg",
      "Luga",
      "Masi",
      "Mission",
      "Simbaluca",
      "Simpatuyo",
      "Villa"
    ]
  },
  {
    "name": "Santo Niño",
    "barangays": [
      "Abariongan Ruar",
      "Abariongan Uneg",
      "Balagan",
      "Balanni",
      "Cabayo",
      "Calapangan",
      "Calassitan",
      "Campo",
      "Centro Norte",
      "Centro Sur",
      "Dungao",
      "Lattac",
      "Lipatan",
      "Lubo",
      "Mabitbitnong",
      "Mapitac",
      "Masical",
      "Matalao",
      "Nag-uma",
      "Namuccayan",
      "Niug Norte",
      "Niug Sur",
      "Palusao",
      "San Manuel",
      "San Roque",
      "Santa Felicitas",
      "Santa Maria",
      "Sidiran",
      "Tabang",
      "Tamucco",
      "Virginia"
    ]
  },
  {
    "name": "Solana",
    "barangays": [
      "Andarayan North",
      "Andarayan South",
      "Bangag",
      "Bantay",
      "Bari",
      "Basi East",
      "Basi West",
      "Bauan East",
      "Bauan West",
      "Calamagui",
      "Calillauan",
      "Carappel",
      "Cattat",
      "Centro Northeast",
      "Centro Northwest",
      "Centro Southeast",
      "Centro Southwest",
      "Danna",
      "Gadu",
      "Iraga",
      "Lanna",
      "Lannig",
      "Lingu",
      "Maddarulug",
      "Maguirig",
      "Malalam-Malacabibi",
      "Maura",
      "Nabbotuan",
      "Naguilian",
      "Nangalisan",
      "Natappian East",
      "Natappian West",
      "Padul",
      "Palao",
      "Parug-parug",
      "Pataya",
      "Sampaguita",
      "Ubong"
    ]
  },
  {
    "name": "Tuao",
    "barangays": [
      "Accusilian",
      "Alabiao",
      "Alabug",
      "Alasig",
      "Angang",
      "Bagumbayan",
      "Barancuag",
      "Battung",
      "Bicchel",
      "Bugnay",
      "Bulagao",
      "Cagumitan",
      "Cato",
      "Centro I",
      "Centro II",
      "Culung",
      "Dagupan",
      "Fugu",
      "Inilangan",
      "Lallafugan",
      "Malummin",
      "Mambacag",
      "Mambit",
      "Masingil",
      "Meti",
      "Naleasin",
      "San Juan",
      "San Luis",
      "San Vicente",
      "Santa Rosa",
      "Taribubu",
      "Villa Laida"
    ]
  },
  {
    "name": "Tuguegarao City",
    "barangays": [
      "Annafunan East",
      "Annafunan West",
      "Atulayan Norte",
      "Atulayan Sur",
      "Bagay",
      "Buntun",
      "Caggay",
      "Capatan",
      "Carig Norte",
      "Carig Sur",
      "Caritan Centro",
      "Caritan Norte",
      "Caritan Sur",
      "Cataggaman Nuevo",
      "Cataggaman Pardo",
      "Cataggaman Viejo",
      "Centro 01 (Bagumbayan)",
      "Centro 02",
      "Centro 03",
      "Centro 04",
      "Centro 05",
      "Centro 06",
      "Centro 07",
      "Centro 08",
      "Centro 09",
      "Centro 10 (Riverside)",
      "Centro 11 (Balzain East)",
      "Centro 12 (Balzain West)",
      "Dadda",
      "Gosi Norte",
      "Gosi Sur",
      "Larion Alto",
      "Larion Bajo",
      "Leonarda",
      "Libag Norte",
      "Libag Sur",
      "Linao East",
      "Linao Norte",
      "Linao West",
      "Namabbalan Norte",
      "Namabbalan Sur",
      "Pallua Norte",
      "Pallua Sur",
      "Pengue-Ruyu",
      "San Gabriel",
      "Tagga",
      "Tanza",
      "Ugac Norte",
      "Ugac Sur"
    ]
  }
] as const

export const CAGAYAN_LOCATIONS = CAGAYAN_LOCATION_TREE.map(
  (municipality) => municipality.name
)
